{{- if .Values.useDeploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uptime-kuma.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uptime-kuma.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.podEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          {{ if .Values.volume.enabled -}}
          volumeMounts:
            - mountPath: /app/data
              name: storage
          {{- end }}
          {{ if .Values.livenessProbe.enabled -}}
          livenessProbe:
            exec:
              command:
                - extra/healthcheck
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds}}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
          {{- end }}
          {{ if .Values.readinessProbe.enabled -}}
          readinessProbe:
            httpGet:
              path: /
              port: 3001
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12  }}
        {{ if .Values.apiSidecar.enabled -}}
        - name: {{ .Values.apiSidecar.name }}
          image: "{{- .Values.apiSidecar.image.repository }}:{{- .Values.apiSidecar.image.tag }}"
          imagePullPolicy: {{ .Values.apiSidecar.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.apiSidecar.securityContext | nindent 12 }}
          env:
          {{- range .Values.apiSidecar.podEnv }}
            - name: {{ .name }}
              value: {{ required "A value must be entered for this apiSidecar.podEnv entry" .value }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.apiSidecar.port}}
              protocol: TCP
          {{ if .Values.apiSidecar.livenessProbe.enabled -}}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.apiSidecar.port}}
            timeoutSeconds: {{ .Values.apiSidecar.livenessProbe.timeoutSeconds}}
            initialDelaySeconds: {{ .Values.apiSidecar.livenessProbe.initialDelaySeconds}}
          {{- end }}
          {{ if .Values.apiSidecar.readinessProbe.enabled -}}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.apiSidecar.port}}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.apiSidecar.readinessProbe.initialDelaySeconds}}
          {{- end }}
          resources:
            {{- toYaml .Values.apiSidecar.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.volume.enabled -}}
      volumes:
      - name: storage
        persistentVolumeClaim:
          {{- if not .Values.volume.existingClaim }}
          claimName: {{ include "uptime-kuma.fullname" . }}-pvc
          {{- else }}
          claimName: {{ .Values.volume.existingClaim }}
          {{- end }}
      {{- end -}}
{{- end -}}
